import assert from 'node:assert/strict';
import * as THREE from './assets/three.module.js';
import { createPedestrians } from './pedestrians.js';
let crimes = 0, attacks = 0;
const scene = new THREE.Scene();
const hooks = { near: () => false, impact() {}, crime: () => crimes++, attack: () => attacks++,
  spawn: () => null, clear: () => true, road: () => false };
const system = createPedestrians(scene, hooks);
const actor = { id: 'local', mode: 'walking', x: 0, z: 0, angle: 0 };
system.sync([{ id: 'one', x: 0, z: -20, angle: 0, style: 0, hp: 300, dead: false }]);
assert.equal(system.target(actor), 'one');
system.punch('one', actor);
assert.equal(system.snapshot()[0].hp, 200);
system.update(.01, true, [actor], []);
assert.equal(attacks, 1);
system.update(.2, true, [actor], []);
assert.equal(attacks, 1, 'knife cooldown prevents repeated hits');
system.punch('one', actor);
system.punch('one', actor);
assert.equal(system.snapshot()[0].dead, true);
assert.equal(crimes, 1);
system.punch('one', actor);
assert.equal(crimes, 1, 'dead NPC cannot die twice');
const clientScene = new THREE.Scene();
const client = createPedestrians(clientScene, hooks);
client.sync(system.snapshot());
assert.equal(clientScene.children[0].visible, false, 'late join hides dead NPC');
system.reset();
assert.equal(scene.children.length, 0, 'reset removes bodies and debris');
system.sync([{ id: 'two', x: 0, z: 0, angle: 0, style: 1, hp: 300, dead: false }]);
system.update(.016, true, [actor], [{ x: 0, z: 10, angle: 0, vx: 0, vz: -100, actorId: 'local' }]);
assert.equal(system.snapshot()[0].dead, true, 'moving car kills NPC');
for (let i = 0; i < 100; i++) system.update(.1, true, [actor], []);
assert.equal(scene.children.length, 0, 'bodies and blocks expire');
console.log('Pedestrian collision, combat, cooldown, sync and cleanup passed');
